export const CHECK_LOGIN_CREDENTIALS = 'CHECK_LOGIN_CREDENTIALS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESFUL = 'LOGIN_SUCCESFUL';
export const LOGOUT_USER = 'LOGIN_SUCCESFUL';
